version: '3.8'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: bd_Farmacia
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: mysql://root:123456@db:3306/bd_Farmacia
    depends_on:
      - db
    command: >
      sh -c "npx prisma migrate deploy && npm start"

volumes:
  mysql-data:
